# @package __global__

# This is the training loop solver
# for the base MusicGen model (text-to-music)
# on monophonic audio sampled at 32 kHz
defaults:
  - musicgen/default
  - /model: lm/musicgen_lm
  - override /dset: musiversal
  - _self_

# efficient_attention_backend: 'xformers'

autocast: true
autocast_dtype: float16

# EnCodec large trained on mono-channel music audio sampled at 32khz
# with a total stride of 640 leading to 50 frames/s.
# rvq.n_q=4, rvq.bins=2048, no quantization dropout
# (transformer_lm card and n_q must be compatible)
compression_model_checkpoint: //pretrained/facebook/encodec_32khz

sample_rate: 32000
channels: 1  # 2

# interleave_stereo_codebooks:
#   use=True

deadlock:
  use: true  # deadlock detection

dataset:
  batch_size: 2  # 32 GPUs
  segment_duration: null
  sample_on_weight: false  # Uniform sampling all the way
  sample_on_duration: false  # Uniform sampling all the way

generate:
  every: 50
  lm:
    use_sampling: true
    top_k: 250
    top_p: 0.0

checkpoint:
  save_last: true
  save_every: 100
  keep_last: 10

optim:
  epochs: 1 #500
  updates_per_epoch: 2000
  optimizer: dadam
  lr: 1
  ema:
    use: true
    updates: 10
    device: cpu

logging:
  log_tensorboard: true

schedule:
  lr_scheduler: cosine
  cosine:
    warmup: 4000
    lr_min_ratio: 0.0
    cycle_length: 1.0
